### ISSUE TITLE
Error On page Udating and saving

### ISSUE THREAD

**Issue by shobhithn7** [riasvdv/statamic-redirect#68]
Hi 

I have updated Statamic Redirect Plugin to the latest version, after this I tried to edit - update the pages (collections), I'm getting this error.

Too few arguments to function Rias\StatamicRedirect\Data\Redirect::findByUrl(), 1 passed in .....\vendor\rias\statamic-redirect\src\Listeners\CreateRedirect.php on line 21 and exactly 2 expected

**Comment by riasvdv** [comment]
This exception should be fixed when updating to 2.3.1

**Comment by shobhithn7** [comment]
It's already in 2.3.1

**Comment by riasvdv** [comment]
This is confirmed fixed in 2.3.1, make sure to composer update
